name: fix_my_trip
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  lottie: ^3.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  intl: ^0.20.2
  flutter_multi_select_items: ^0.4.3
  google_maps_flutter: ^2.12.3
  provider: ^6.1.5
  flutter_svg: ^2.2.0
  firebase_auth_rest: ^2.1.1
  fl_chart: ^1.0.0
  image_picker: ^1.1.2
  flutter_google_places_sdk: ^0.4.2+1
  google_maps: ^8.1.1
  universal_html: ^2.2.4
  google_places_flutter: ^2.1.0
 
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  firebase_storage: ^12.4.10
  video_player: ^2.10.0
  flutter_vector_icons: ^2.0.0
  awesome_snackbar_content: ^0.1.8
  font_awesome_flutter: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  
    - assets/images/

  
fonts:
  - family: TTBlueScreens
    fonts:
      - asset: assets/fonts/TTBlueScreens-Regular.ttf
  - family: BeautifullyDelicious
    fonts:
      - asset: assets/fonts/BeautifullyDelicious-Regular.ttf